name: GitHub Action

on:
  push:
    tags: v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run build task
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.REMOTE_TARGET }}
            git fetch --all
            git reset --hard ${{ github.ref }}
            git pull --force origin ${{ github.ref }}
            npm i
            npm run build
            lsof -i :13306 | awk 'NR!=1 {print $2}' | xargs -r kill
            nohup node dist/index.js > ../app.log 2>&1 &
